_wandb:
    value:
        cli_version: 0.28.0
        e:
            4bnsllcfe8wkrcqw9x8cs4ik6xhh64sf:
                apple:
                    ecpuCores: 6
                    gpuCores: 8
                    macModel: Mac16,12
                    memoryGb: 16
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "1073741824"
                codePath: scripts/train_distil.py
                codePathLocal: scripts/train_distil.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "245107195904"
                        used: "155910635520"
                email: w1ndrunn3rr@gmail.com
                executable: /Users/kuba/Home/projekty/distil_act/.venv/bin/python3
                git:
                    commit: b63a2e57e163df9b6a3c0476995d3bc7e853e432
                    remote: git@github.com:jgilewicz/distil_act.git
                host: MacBook-Air-Kuba.local
                memory:
                    total: "17179869184"
                os: macOS-26.5.1-arm64-arm-64bit-Mach-O
                program: /Users/kuba/Home/projekty/distil_act/scripts/train_distil.py
                python: CPython 3.14.4
                root: /Users/kuba/Home/projekty/distil_act
                startedAt: "2026-07-05T18:59:55.954407Z"
                writerId: 4bnsllcfe8wkrcqw9x8cs4ik6xhh64sf
        m: []
        python_version: 3.14.4
        t:
            "1":
                - 1
                - 41
                - 49
            "2":
                - 1
                - 41
                - 49
            "3":
                - 16
                - 41
            "4": 3.14.4
            "5": 0.28.0
            "12": 0.28.0
            "13": darwin-arm64
action_dim:
    value: 6
batch_size:
    value: 32
beta:
    value: 0.05
chunk_size:
    value: 50
embed_dim:
    value: 256
hf_filename:
    value: act_model_final.pt
hf_repo_id:
    value: jgilewicz/distil_act_teacher
joint_dim:
    value: 6
latent_dim:
    value: 128
log_interval:
    value: 1000
lr:
    value: 0.0001
max_steps:
    value: 50000
nhead:
    value: 8
num_cameras:
    value: 2
num_layers:
    value: 4
num_workers:
    value: 8
save_interval:
    value: 10000
val_ratio:
    value: 0.1
wandb:
    value:
        entity: jg_projects
        project: distil_act
warmup_steps:
    value: 1000
